name: eso
description: 亦搜，亦看，亦闻

version: 1.20.16+12016

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers:
    path: modules/audioplayers
  flutter_js:
    path: modules/flutter_js
  flutter_webview:
    path: modules/flutter_webview
  webview_flutter:
    path: modules/webview_flutter
  xpath_parse:
    path: modules/xpath
  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/file_chooser
  about: ^1.2.0
  archive: ^2.0.13
  battery: ^1.0.7
  cached_network_image: ^2.3.3
  crypto: ^2.1.5
  cupertino_icons: ^1.0.0
  device_info: ^0.4.2+9
  dlna: ^0.0.5
  encrypt: ^4.1.0
  equatable: ^1.2.5
  event_bus: ^1.1.1
  fast_gbk: ^0.1.2+1
  file_picker: ^2.0.10
  floor: ^0.17.0
  flutter_colorpicker: ^0.3.4
  flutter_share: ^1.0.2+1
  flutter_slidable: ^0.5.7
  html: ^0.14.0+4
  http: ^0.12.2
  image_gallery_saver: ^1.6.1
  intl: ^0.16.1
  json_path: ^0.2.0
  matrix_gesture_detector: ^0.1.0
  oktoast: ^2.3.2
  outline_material_icons: ^0.1.1
  package_info: ^0.4.3
  path_provider: ^1.6.21
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  provider: ^4.3.2+2
  pull_to_refresh: ^1.6.2
  screen: ^0.0.5
  shared_preferences: ^0.5.12+2
  url_launcher: ^5.7.7
  uuid: ^2.2.2
  video_player: ^0.11.1+2
  sqflite_common_ffi: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  floor_generator: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - README.md
    - LICENSE
    - lib/assets/
  fonts:
    - family: fonticons
      fonts:
        - asset: fonts/fonticons.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
