name: eso
description: 亦搜，亦看，亦闻

version: 1.12.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
  cupertino_icons: ^0.1.3
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  equatable: ^1.1.1
  url_launcher: ^5.4.2
  fast_gbk: ^0.1.2+1
  flutter_share: ^1.0.2+1
  crypto: ^2.1.4
  html: ^0.14.0+3
  # wakelock: ^0.1.3
  video_player:
    git: 
      url: git://github.com/cbenhagen/plugins.git
      ref: video_player_macos
      path: packages/video_player/video_player
  path_provider: ^1.6.5
  audioplayers: ^0.15.1
  encrypt: ^4.0.0
  archive: ^2.0.13
  webview_flutter: 0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
