name: eso
description: 亦搜，亦看，亦闻

version: 1.11.5+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  equatable: ^0.6.1
  url_launcher: ^5.1.2
  fast_gbk: ^0.1.1+1
  flutter_share: ^1.0.2+1
  crypto: ^2.1.3
  html: ^0.14.0+3
  wakelock: ^0.1.3
  video_player: ^0.10.2+5
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
