name: ESO Build

# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  schedule:
    # 美国时间每周一5时（中国时间每周一13时）
    - cron:  '0 5 * * 1'
  watch:
    types: [started]

jobs:
  Apk_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ESO Project
        uses: actions/checkout@v2
        with:
          path: eso

      - name: JDK Install
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Flutter SDK Install
        run: |
          git clone https://github.com/flutter/flutter.git -b master _flutter
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"

      - name: Get Flutter Version
        run: flutter --version

      - name: Fix build.gradle
        run: |
          echo "insert [ndkVersion '21.3.6528147']"
          sed -i "39a\    ndkVersion '21.3.6528147'" $GITHUB_WORKSPACE/eso/android/app/build.gradle

      - name: Build Apk
        run: |
          cd $GITHUB_WORKSPACE/eso
          flutter pub get
          flutter build apk --split-per-abi -v

      - name: Upload Android APP
        uses: actions/upload-artifact@v2
        with:
          name: ESO_APK
          path: eso/build/app/outputs/apk/release/*.apk
          if-no-files-found: error

  Windows_Build:
    runs-on: windows-latest
    steps:
      - name: Checkout ESO Project
        uses: actions/checkout@v2
        with:
          path: eso

      - name: JDK Install
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Flutter SDK Install
        uses: subosito/flutter-action@v1
        with:
          channel: dev

      - name: Flutter Channel Switch
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-windows-desktop

      - name: Build Windows Desktop
        run: |
          cd eso
          del pubspec.yaml
          move pubspec.windows.yaml pubspec.yaml
          flutter pub get
          flutter build windows -v

      - name: Upload Windows Desktop
        uses: actions/upload-artifact@v2
        with:
          name: ESO_WINDOWS
          path: eso/build/windows/runner/Release
          if-no-files-found: error

  Macos_Build:
    runs-on: macos-latest
    steps:
      - name: Checkout ESO Project
        uses: actions/checkout@v2
        with:
          path: eso

      - name: JDK Install
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Flutter SDK Install
        run: |
          git clone https://github.com/flutter/flutter.git -b master _flutter
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"

      - name: Get Flutter Version
        run: |
          flutter --version
          flutter config --enable-macos-desktop

      - name: Build Macos Desktop
        run: |
          cd eso
          flutter pub get
          flutter build macos -v

      # 太大 暂时不用
      # - name: Upload Macos Desktop
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ESO_MACOS
      #     path: eso/build/macos/Build/Products/Release/*.app/
      #     if-no-files-found: error